### ISSUE TITLE
Error adding allele

### ISSUE THREAD

**Issue by RomuloVianna** [DKMS-LSL/typeloader#11]
Every time that I try to upload a DPA1 sequence I get the same error:

Error while processing the sequence
IndexError('list index out of range',)

[dpa-test.txt](https://github.com/DKMS-LSL/typeloader/files/3350482/dpa-test.txt)
(the file is in txt because fasta extension is not supported by GitHub)

**Comment by bmschoene** [comment]
We do not yet do DPA1 in our lab, so we have not experimented with this. 
We currently support & have tested:

 * HLA-A, B, C, DRB1, DQB1, DPB1
 * KIR (all loci)
 * MICA and MICB

However, I will try to look into your file and see if it's something easy to fix in the next release.

**Comment by bmschoene** [comment]
Adding HLA-DPA1 seems to be not a big deal, so we will include it in the next release, together with DQA1. 

As a warning, though: IPD generally requires genomic sequences to include at least one base of each UTR. The file you uploaded is missing the complete 3' UTR, though. So TypeLoader would reject the sequence as it is (with a clear message). I have tested it with an artificially elongated sequence and it works there, though. So if you can manage to place your primers so that you can sequence at least the first base of the 3'UTR, you should be able to submit these alleles with the next TypeLoader release, which we're planning to release within the next 2 weeks.

I'll let you know when the new release is out.

**Comment by RomuloVianna** [comment]
Great!

**Comment by bmschoene** [comment]
@RomuloVianna Sorry, the new release will take a bit longer. It is ready per sé, but unfortunately I cannot upload it on GitHub because the installer is now bigger than 100 MB (because of the changed ENA interface), and I'm leaving for vacation tomorrow. 
I will find a way to get it released as soon as possible, and I'll notify you once it happens.
Sorry about the delay.

**Comment by bmschoene** [comment]
@RomuloVianna I have just uploaded the new release. This should solve your problem, I hope.
If you continue to encounter any problems, just create another issue. :-)
