### ISSUE TITLE
typeloader/user_manual/pretypings.md

### ISSUE THREAD

**Issue by steletvinicius** [DKMS-LSL/typeloader#12]
When describing the instructions to prepare the pretypings file, it says it is mandatory to report the following HLA loci:

"
Required loci
The following loci are the minimum acceptable pretyping profile for IPD submissions:

HLA-A
HLA-B
**HLA-DQB1**
the gene you are submitting
However, IPD strongly encourages adding as much genotyping data about the sample as you have.
"
However, according to Conditions for acceptance of new allele sequences at https://www.ebi.ac.uk/ipd/imgt/hla/subs/submit.html

12 - The complete HLA type for HLA-A, -B, **-DRB1** genes must be submitted for the material in which a novel allele has been defined. In addition, the sample should have been characterized for the second allele at the locus of interest in a heterozygous individual.

HLA- DRB1 gene typing is mandatory; not HLA-DQB1.

I though it was a mystyping at the instructions section but Typeloader is really taking HLA-DQB1 typing as mandatory. 

Could you please update that as I have many intronic novelties to submit from samples with only HLA-A, -B, -DRB1 typing knwon.

**Comment by bmschoene** [comment]
You are right! Sorry about that, I will fix it in the next release.

How urgent is this for you? The bugfix is easy, but generating a new Windows installer for the new version takes some time, and I'm currently working on a new version anyway, which should hopefully be released within the next month or so. Is that soon enough for you?

(Nice to hear someone is actually trying to use the software. :-D)

**Comment by bmschoene** [comment]
It's great to hear you are so enthusiastic about TypeLoader! I'm looking very much forward to seeing all those Brazilian alleles in the database! Spreading the word sounds awesome to me! :-D
(And if you do end up making tutorials in Portuguese, maybe we can make these generally available/link them from here?)

We are mostly developing the software for our internal use, but it would be a pity if others wouldn't use it, too. :-)

_> However, I could not perform a bulk submission because after two requests for being a Bulk submitter, I have got no answer from IMGT staff. No even a Yes or NO. ;-(_

That is unfortunate, though, sadly, not unheard of. IPD is always very busy and often understaffed. :-(
Have you submitted any alleles manually, yet? They will pretty definitely ask you to do that for a couple of alleles anyway, to be able to judge the quality and credibility of your sequences. So I strongly recommend you go ahead and submit some of these sequences manually, and keep sending emails to them (the address is correct), including a reference to the alleles you have submitted, and ask them for a status update on your request.
I'm very sorry it is necessary to jump through those hoops in order to submit TypeLoader files to the IPD, but this is their current policy to make as sure as possible that people don't submit junk, and we have little to no influence on it.

As a workaround to the actual issue here (until the new release comes), you could re-label the column "DQB1" as "DRB1" in your pretypings file and create the IPD files with that, then correct it manually in the generated IPD files (as they are text files). Just make very sure to actually do that, so you don't accidentally submit wrong pretypings. :-P

_> Regarding new versions:
every time I open the software, It tells me there is a new version available
but I could not find the respective Windows installer to upgrade from 2.4.0 to 2.4.1._

Erm, that is a kind of semi-bug. The only difference between 2.4.1 and 2.4.0 is that the installer is now distributed via https://github.com/DKMS-LSL/typeloader/releases. But I did not build a new installer for that. So 2.4.0 and 2.4.1 are the same thing, but on Startup, TypeLoader notices that there _is_ a 2.4.1, hence the popup.

Which means you can ignore this as long as it doesn't announce any version greater than 2.4.1. Sorry about the confusion!

**Comment by steletvinicius** [comment]
I have been using Typeloader as an easier way to do the first submission step (Ena submission)
It is been great! Few clicks and it is done.
Unfortunately, The automation of the second step (bulk submission) is just available for large number submitters according to IMGT staff ...  : (
Anyways,
There are some "bugs" regarding closer allele determination that I could share if you want.
Could you share your e-mail?


![image](https://user-images.githubusercontent.com/59885793/73300392-b05b8b00-41ef-11ea-9097-349de59576cb.png)

**Comment by bmschoene** [comment]
_Unfortunately, The automation of the second step (bulk submission) is just available for large number submitters according to IMGT staff ... : (_

Sorry to hear that. We hope they will come around to revise this choice eventually (since we feel strongly that manual copying into webforms is a likely error source that should be avoided), once more people are contacting them about submitting via TypeLoader. But until they do, there's little we can do about it. :-(

_Anyways,
There are some "bugs" regarding closer allele determination that I could share if you want.
Could you share your e-mail?_

Actually, it would be great if you'd just open an issue here for each bug you find. This way, stuff doesn't get lost and I can keep you updated to the status of each bug.
