### ISSUE TITLE
Delete Alleles

### ISSUE THREAD

**Issue by steletvinicius** [DKMS-LSL/typeloader#14]
I have added some alleles under the wrong project.

To correct this mistake, I use the right-clicking option on the left side menu.

However, even after choose to delete the allele and confimr my admin password,
It was not deleted.

What should I do in addition to that to delete those alleles?
Is it possible to change to which project an specific allele is linked after import to typeloader
before ENA submission?

**Comment by bmschoene** [comment]
"Your" admin password is not going to work here. The password request is a measure to make sure users don't do this lightheartedly / only the "TypeLoader-expert" of a team should do this - it should be someone who has an idea of the consequences. (Like, if the allele has already been submitted, it will clogg up ENA's servers, and deletion of these alleles should be requested from ENA.) 

Since that person for your lab is probably you, this is the admin password required: ``ichdarfdas``. 

(It's not intended to be a secret - it's hardcoded into the code, after all, so someone who knows how to read Python code will be able to dig it up, anyway. It's just not meant for casual users in a multi-user lab, so it requires at least some digging to find this. Googling for this to find this answer shows sufficient effort, I think, so putting this information here is good.)

_Is it possible to change to which project an specific allele is linked after import to typeloader
before ENA submission?_

No. (It would be possible to implement, but the effects are not small, and it shouldn't be necessary all that often. So there's currently no plan to implement this.) 
Deleting them and re-uploading them to the correct project is indeed the way to go.

Let me know if it works with the right password. :-)

**Comment by steletvinicius** [comment]
I understand your point regarding multi-user facilities.
As in my lab, I am the (alone) user of Typeloader, I can take it.

I did the exclusion and it worked perfectly.
Thank's.

**Comment by bmschoene** [comment]
Great. :-)
