### ISSUE TITLE
Support for Non-classical HLA submission

### ISSUE THREAD

**Issue by steletvinicius** [DKMS-LSL/typeloader#18]
Are you considering to include on feature updates of TypeLoader support for non-classical HLA submissions, like HLA-E, -F, -G, -H?

**Comment by bmschoene** [comment]
HLA-E is already supported.

The others I can include in a future release if there's demand. Including new HLA loci is not a big deal, but it does increase the reference database size (and hence times for sequence upload to TypeLoader as well as IPD file creation, albeit not dramatically so). So I don't do that unless there is demand, and we don't do any of these loci (except for HLA-E) here. :-)

If you need any of these genes, let me know which and I'll include them in the next release.

**Comment by steletvinicius** [comment]
I have made my very first HLA-E submission to ENA right now. It worked.
It is a consequence of starting to run hybrid capture NGS that provides coverage for many non-classical class I HLA genes and
MICA/MICB.
After analyzing one single batch of 24 Brazilian samples 
we detected novel sequences for HLA-E (1), -F (1), -H(1), -K(2), And we can also contribute to IMGT with sequence extensions,
especially for HLA-G and -J.

Suggestion: If adding compatibility for non-classicals on the main TypeLoader installation is going to bother other users with extra processing time with no gain,
it would be possible to provide this database as an extension or additional TypeLoader feature?
In this case, Users could choose to install it or not according to their demands.
It is easy to suggest without being aware of the technical limitations... I know...
From my side, I can tell you that if non-classical HLAs support get implemented,
It will help me a lot.

I hope you can find a way. Greetings from Brazil!  :-)

**Comment by bmschoene** [comment]
Since neither of these genes comes with a gazillion alleles, I don't think the additional processing time is a big thing. I can only gues, but I'm thinking the order of magnitude should be < 1 sec per allele uploaded.

Of course, it would be possible to let users generally restrict their databases to the genes they deal with. But I don't really think the gain of time per sample would justify the effort.

I have put these genes on my list. You should get them with the start-of-September release that has to happen anyway, to accomodate for ENA's API changes.

**Comment by bmschoene** [comment]
The new release 2.8.2 covers the genes you requested. Have fun! :-)
