### ISSUE TITLE
ENA rejected your files

### ISSUE THREAD

**Issue by steletvinicius** [DKMS-LSL/typeloader#19]
Right after updating TypeLoader, I have:

1. Created two projects;
when trying to register then on ENA database, it returned an error message on the first attempt
and worked on the second tentative

2. Imported a new sequence to one of the projects: OK

3. Submitted this sequence to ENA
First attempt: FAILED*
Second Attempt: FAILED*

**(while writing this message, I was running the third attempt and IT WORKED!)**

* The message below was shown right after failed submissions to ENA
==============================================================
ERROR: ENA rejected your files (validation failed):

ERROR: I/O error on POST request for "https://www.ebi.ac.uk/ena/auth/login": Unexpected end of file from server; nested exception is java.net.SocketException: Unexpected end of file from server

The complete submission has been rejected.
==============================================================

**Comment by bmschoene** [comment]
So it worked in the end? 
Then I assume the problem is on ENA's side and I can do nothing about that.

Has all of this occurred on one day, or over a longer period?

ENA has recently announced working on updating stuff on their side, which will require me to adjust TypeLoader to cope with it. However, the changes were not supposed to be effective until September 1st. But maybe they accidentally created a bug while working on their stuff?

Can you please let me know whether the problem still persists in a day or so?

**Comment by steletvinicius** [comment]
Yes, it worked. I just reported thinking it would be helpful t track if it is happening with other users.

Yes, it occurred during one afternoon (yesterday). If the problem persists on future submissions, I will let you know.

**Comment by bmschoene** [comment]
Good thinking, and thanks!

**Comment by bmschoene** [comment]
Seems to have resolved itself.
