### ISSUE TITLE
Reference update request after login

### ISSUE THREAD

**Issue by steletvinicius** [DKMS-LSL/typeloader#21]
Hi,

I have noticed that every time I log in, Typeloader requests reference update.
After running automatic update, It returns a success message informing that reference 3.43 is the active.

Is 3.43 IPD-IMGT/HLA reference database the most recent one?
I am not so sure but I think I remember running a similar update and, after that, 3.45 version was installed...

However, the real issue is that EVERY TIME I log in I have to run an update which in fact is updating nothing.
It just keeps the previously installed version (3.43).

Is the software trying to download version 3.45 with no success?

**Comment by bmschoene** [comment]
The reference TypeLoader is using is istill stuck at 3.43. Sorry about that. I will try to get it updated after I and the colleague I need for checks are back from vacation, which is early September.

The issue you have (with the update required every time) occurs when TypeLoader's local reference files are changed in a way that TypeLoader notices, e.g., by a nightly cleanup/backup operation etc. 

What happens: On startup, TypeLoader checks whether it needs any update. To do this, it calculates the MD5 checksum of the existing hla.dat and KIR.dat file and compares them with those from the reference repository. If these don't match, it asks you to update.

These checksums should, in theory, only change if the file content or name etc. changes, which is why they are used to detect if changes have happened. However, it seems that some other operations also can change these MD5 checksums, and therefore TypeLoader thinks there have been changes even though none have occurred.

(As you can probably tell, the same thing is happening in our lab.) 

I have this on my "to solve" list, but I haven't gotten around to it. The main trouble is that IPD sometimes changes these reference files without changing the version number, so I haven't found an alternative way to make sure all changes are registered.... OTOH, all of this was designed and implemented before we decided to use not the IPD repos directly as references but make forks of them which have to undergo our quality checks (because sometimes, IPD pushes broken reference data which wrecked havoc with TypeLoader in the past). So we could probably simply circumnavigate this... 

But I don't know when I will get around to this. Until then, I'm afraid you'll have to bear. Sorry. :-(

**Comment by steletvinicius** [comment]
No problem at all.
I was checking if it was a possible issue on my Typeloader instalation.

**Comment by bmschoene** [comment]
FYI, we have finally managed to check the current IPD release and update TypeLoader's reference database to 3.45.
