### ISSUE TITLE
Restore backup data after PC format and clean Install Windows 10

### ISSUE THREAD

**Issue by steletvinicius** [DKMS-LSL/typeloader#23]
Hi,

I have made a backup from TypeLoader Submissions (folder AlleleSubmissions_Typeloader).
How shall I proceed to restore this data on a fresh new installation?
Just copy the old data and paste on the similar folder?

Another question: I have realized that I did not made a full backup from my submissions to IPD...
Which information from my submissions can I recover accessing my ENA account?

**Comment by bmschoene** [comment]
If I understand you correctly, you have a new TypeLoader installation (because the old one is broken or you switched computers etc.) and would like to access your data from the old installation?

Is AlleleSubmissions_Typeloader the path that you specified as data path during your initial TypeLoader installation?

Since the data folder is decoupled from the TypeLoader installation itself, you should be able to simply re-install TypeLoader and give it the same path to the old data folder (or copy that folder to some other place and use the path to that copy) and then it should find everything, including the user data with all projects and files. You will have to re-enter your settings during installation, though, as these are stored with the TypeLoader installation, not the data.

Your IPD and ENA files should also be right in there.

**Comment by bmschoene** [comment]
FWIW, someone reported a problem with using the current installer for a fresh installation (#20), so you may run into trouble there. Just as a warning.
There will be a new TypeLoader installation in late October. (Has to be, because ENA announced a breaking change to their command line interface, so the current TypeLoader versions will stop working on November 1st.)

**Comment by steletvinicius** [comment]
I saw this opened issue (thanks for keeping it open).
Following the submitter provisory solution ("I found that the installer works if I choose "No" in "update an existing TypeLoader installation?" ) the installation proceeded without problems.
Indeed, I was able to "restore" my backup data. Thanks.
