### ISSUE TITLE
Issue with updating reference HLA/KIR database

### ISSUE THREAD

**Issue by naser-ellagta** [DKMS-LSL/typeloader#27]
Hi,

We are currently trying to implement Typeloader into our laboratory but we are unable to upload any data files as the program is unable to download the reference files. This is the first time we are trying to use Typeloader, and are currently using the latest version (v 2.11.1). I've attached a screenshot of the error message as well as the log file.

Thanks in advance :))

[20220104_081957.log](https://github.com/DKMS-LSL/typeloader/files/7804666/20220104_081957.log)

![reference refresh error](https://user-images.githubusercontent.com/97069510/147993940-d812748c-c542-48db-8ab1-4439dace27b2.JPG)

**Comment by bmschoene** [comment]
I'm glad you've decided to use TypeLoader! :-) Let's see if we can work this out.

I'm pretty sure the problem you're seeing is not TypeLoader itself but something about your internet connection, possibly a firewall or proxy thing. According to the log, not only did the dowloading of the reference file (which is sizeable, so that might have been due to a slow connection) time out, but already the attempt to check for a newer version does the same (which is a very quick lookup).

Can you please try opening [this link](https://raw.githubusercontent.com/DKMS-LSL/typeloader/master/typeloader2/__init__.py) in your browser? It should show you a text file with contents like author, maintainers, license and the current version etc.
(This is the file that your TypeLoader tried and failed to reach to check for the newest version.)

I'm guessing this will probably work, but want to make sure.

If it does work, can you ask your IT people whether your firewall settings may be prohibiting installed software from reaching out to GitHub, and if they can do anything about it? And if there is anything I as the programmer of that software can implement to help? (E.g., TypeLoader already lets you enter a proxy server (either during install, or afterwards in your user settings). But so far, this is only used for connecting to ENA, which is the only point where we have needed it in the past. But I could probably pass the same proxy to the GitHub-connection attempt, if that helps.)

**Comment by naser-ellagta** [comment]
Hi Bianca, 
Thanks for getting back to us! 
As we are a government organisation, you're right in assuming there are firewall settings in place that restrict access of installed software on our systems. We had a previous issue where a timeout error occurred when we tried to create a new ENA project using Typeloader but this was resolved by entering a proxy server. Given what you said, I think it may be likely that this is an issue with the Github-connection attempt, as the error occurs when the program attempts to communicate with Github.
Let me know what you think
Thank you :))

**Comment by bmschoene** [comment]
I agree. I'll see that I pass these through the proxy, as well, then. Hopefully, I'll have a test installer for you to try out tomorrow.

**Comment by bmschoene** [comment]
Here's a test installer for you: [click to download](https://dkms-lab.ftapi.com/download/419da76c-aa78-4957-b67c-1e8f6c339f24).

Please use it to update your installation and let me know whether it fixes your problem?

**Comment by naser-ellagta** [comment]
Thanks for your help Bianca!

The issue with updating the reference files seems to have resolved, but now we are presented with another issue when submitting files to ENA. I've attached a screenshot of the error message as well as the log file.

Thanks in advance :)
[20220107_090632.log](https://github.com/DKMS-LSL/typeloader/files/7825626/20220107_090632.log)

![Capture](https://user-images.githubusercontent.com/97069510/148475179-54414ec6-54fe-4926-9277-d12b3855aa23.JPG)

**Comment by bmschoene** [comment]
Ah, I see. The submission of sequences to ENA happens via their command line tool webin-CLI, which is a java tool that ENA provides and TypeLoader brings along. That one didn't happen through the proxy because it's not a connection that TypeLoader itself opens.

I wasn't sure how to pass the proxy to this, so I didn't. But I think I may have figured it out. 🤞 

Here's another beta installer for you: [click](https://dkms-lab.ftapi.com/download/5a86d7ba-e55f-4824-a5c2-e81de185b8f1)

**Comment by naser-ellagta** [comment]
The same issue is still persisting - is there anything we can do on our end to resolve this issue, or does the webin-CLI tool need to be modified so that it can work through the proxy server?

**Comment by naser-ellagta** [comment]
Now we're getting a different error message which reads

ERROR: Failed to connect to webin.ebi.ac.uk using FTP. Failed to upload files to webin.ebi.ac.uk because of a system error.

Not sure what this means

I've also attached the log file
[20220111_094035.log](https://github.com/DKMS-LSL/typeloader/files/7843027/20220111_094035.log)

**Comment by bmschoene** [comment]
@DavidTBrookes we already have an issue for this problem here.
Further communication via email.
