### ISSUE TITLE
Null allele due to insertion in intron 1 of DRB1

### ISSUE THREAD

**Issue by stephencheunghk** [DKMS-LSL/typeloader#39]
Hello,

I would like to report/inquiry an issue about false detection of null allele due to an insertion in intronic position.

When I tried to add new allele sequence with an exonic mismatch and intronic insertion for DRB1*09:01:02:03, it was detected by Typeloader as null allele. 
After a few rounds of testing, it seems that the insertion of T at the repetitive T region of intron 1 (g.5041-5054 of DRB1*09:01:02:03) leads to the detection of null allele. The insertion causes 1 bp shift in the features, so it becomes a null allele. e.g. 147..246 of exon 1 becomes 146..245 for exon 1 (as shown below). When I removed the T insertion, it was detected as a normal new allele. 

Is it okay to directly amend the feature tables in the "(3) Check ENA files and save alleles" step? 

**With T insertion:**
DE   Homo sapiens,  HLA-DRB1 pseudogene, cell line Test_test_DRB1_1, null allele HLA-DRB1*09:new
CC   (file created with TypeLoader version 2.14.2 based on HLA release 3.54.0)
XX
FH   Key             Location/Qualifiers
FH
FT   source          1..15395
FT                   /organism="Homo sapiens"
FT                   /mol_type="genomic DNA"
FT                   /cell_line="Test_test_DRB1_1"
FT   CDS             join(146..245,10561..10830,13067..13348,14046..14156,14632..14655,15345..15358)
FT                   /codon_start=1
FT                   /gene="HLA-DRB1"
FT                   /allele="HLA-DRB1*09:new"
FT                   /note="MHC class II antigen null allele"
FT                   /pseudogene="allelic"
FT   exon            1..245
FT                   /number=1
FT                   /gene="HLA-DRB1"
FT                   /allele="HLA-DRB1*09:new"
FT   intron          246..10560
FT                   /number=1
FT                   /gene="HLA-DRB1"
FT                   /allele="HLA-DRB1*09:new"
FT   exon            10561..10830
FT                   /number=2
FT                   /gene="HLA-DRB1"
FT                   /allele="HLA-DRB1*09:new"
FT   intron          10831..13066
FT                   /number=2
FT                   /gene="HLA-DRB1"
FT                   /allele="HLA-DRB1*09:new"
FT   exon            13067..13348
FT                   /number=3
FT                   /gene="HLA-DRB1"
FT                   /allele="HLA-DRB1*09:new"
FT   intron          13349..14045
FT                   /number=3
FT                   /gene="HLA-DRB1"
FT                   /allele="HLA-DRB1*09:new"
FT   exon            14046..14156
FT                   /number=4
FT                   /gene="HLA-DRB1"
FT                   /allele="HLA-DRB1*09:new"
FT   intron          14157..14631
FT                   /number=4
FT                   /gene="HLA-DRB1"
FT                   /allele="HLA-DRB1*09:new"
FT   exon            14632..14655
FT                   /number=5
FT                   /gene="HLA-DRB1"
FT                   /allele="HLA-DRB1*09:new"
FT   intron          14656..15344
FT                   /number=5
FT                   /gene="HLA-DRB1"
FT                   /allele="HLA-DRB1*09:new"
FT   exon            15345..15395
FT                   /number=6
FT                   /gene="HLA-DRB1"
FT                   /allele="HLA-DRB1*09:new"

**Without T insertion:**
DE   Homo sapiens,  HLA-DRB1 gene for MHC class II antigen, cell line Test_test_DRB1_1, allele HLA-DRB1*09:new
CC   (file created with TypeLoader version 2.14.2 based on HLA release 3.54.0)
XX
FH   Key             Location/Qualifiers
FH
FT   source          1..15394
FT                   /organism="Homo sapiens"
FT                   /mol_type="genomic DNA"
FT                   /cell_line="Test_test_DRB1_1"
FT   CDS             join(147..246,10561..10830,13067..13348,14046..14156,14632..14655,15345..15358)
FT                   /codon_start=1
FT                   /gene="HLA-DRB1"
FT                   /allele="HLA-DRB1*09:new"
FT                   /product="MHC class II antigen"
FT                   /function="antigen presenting molecule"
FT   exon            1..246
FT                   /number=1
FT                   /gene="HLA-DRB1"
FT                   /allele="HLA-DRB1*09:new"
FT   intron          247..10560
FT                   /number=1
FT                   /gene="HLA-DRB1"
FT                   /allele="HLA-DRB1*09:new"
FT   exon            10561..10830
FT                   /number=2
FT                   /gene="HLA-DRB1"
FT                   /allele="HLA-DRB1*09:new"
FT   intron          10831..13066
FT                   /number=2
FT                   /gene="HLA-DRB1"
FT                   /allele="HLA-DRB1*09:new"
FT   exon            13067..13348
FT                   /number=3
FT                   /gene="HLA-DRB1"
FT                   /allele="HLA-DRB1*09:new"
FT   intron          13349..14045
FT                   /number=3
FT                   /gene="HLA-DRB1"
FT                   /allele="HLA-DRB1*09:new"
FT   exon            14046..14156
FT                   /number=4
FT                   /gene="HLA-DRB1"
FT                   /allele="HLA-DRB1*09:new"
FT   intron          14157..14631
FT                   /number=4
FT                   /gene="HLA-DRB1"
FT                   /allele="HLA-DRB1*09:new"
FT   exon            14632..14655
FT                   /number=5
FT                   /gene="HLA-DRB1"
FT                   /allele="HLA-DRB1*09:new"
FT   intron          14656..15344
FT                   /number=5
FT                   /gene="HLA-DRB1"
FT                   /allele="HLA-DRB1*09:new"
FT   exon            15345..15394
FT                   /number=6
FT                   /gene="HLA-DRB1"
FT                   /allele="HLA-DRB1*09:new"

Thanks for developing Typeloader, it is a great tool!

**Comment by bmschoene** [comment]
Thanks you for the feedback! It's always great to hear from people who are using TypeLoader. :-)

It's had to evaluate without having the sequence to look at. Normally, I would think that an insertion within an intron should not shift the reading frame and therefore not create a null allele. But in the end, the annotation is done with BLAST, and the parameters that work for 99% of sequences may sometimes fail for some edgecases. (So far, I have only seen it fail in one case where there was a huge deletion in comparison to the closest known allele.)

_Is it okay to directly amend the feature tables in the "(3) Check ENA files and save alleles" step?_

If you're confident that you know which changes to make to keep things annotated correctly, yes.

Be aware, though, that you will sadly probably have to do the same thing again when you do IPD submission, as there is a re-BLAST-step in there... :( (Maybe make a fake-IPD-submission on your test account with the "no T insertion" variant to see the outcome?)

If you would like me to look into the allele and see if anything can be done to adjust TypeLoader so it can handle your sequence (and others with the same problem) correctly, I will need the sequence. You're welcome to send it to me via email or post it here. 
I cannot promise that I can fix it, though. And if I can, it'll take a while, because TypeLoader is not my main project anymore. But I can look into it.

**Comment by stephencheunghk** [comment]
I artificially created a DRB1*09:01:02:03 sequence with a T insertion at position 5202 (attached, changed to *.txt for uploading).
[DRB1_09_01_02_03_insT.txt](https://github.com/DKMS-LSL/typeloader/files/13947407/DRB1_09_01_02_03_insT.txt)
It also makes the Typeloader to detect it as a null allele.

_Is it okay to directly amend the feature tables in the "(3) Check ENA files and save alleles" step?
If you're confident that you know which changes to make to keep things annotated correctly, yes._
I tried to amend the features and clicked "Save changes!", but turns out the ena.txt file remains unchanged.

I may just manually submit the sequence manually if it is hard to fix :)

Thanks for your efforts!

**Comment by bmschoene** [comment]
Thanks!
Huh. This is weird, that it doesn't save the changes... 
Of course, you can always manually edit the saved ENA file, but that's not how thing should work... *sighs*

Manually submitting this allele might actually be the quickest way to get it submitted... :-(

But I will look into it and get back to you as soon as I can free the time.

**Comment by bmschoene** [comment]
I finally found time to look into this issue.

The actual problem here is not the insertion in the intron itself, but that because of it TypeLoader chooses a different closest allele than you think (DRB1*09:01:02:11), which has the same intron insertion. Unfortunately, the known sequence of this allele in the database is 1 bp shorter at the beginning of UTR5: 
![image](https://github.com/DKMS-LSL/typeloader/assets/43027482/be24271b-9790-4139-a34c-35dec53d25ef)
![image](https://github.com/DKMS-LSL/typeloader/assets/43027482/ff5ddb92-73d8-4f41-a865-6933e000cf6e)
For some reason, TypeLoader gets this tangled and uses the reference's exon/intron boundary positions instead of those from the alignment of the two. Which is why the positions are all off by 1 bp.

Unfortunately, properly untangling this without breaking existing known edgecases appears to be a huge ammount of work with the current state of the code. It requires some serious cleanup work on the heart of the code base. And sadly, we currently can't invest the manpower to do this, nor in the upcoming 1-2 years. :-(

So for now, all I could do was add a warning that will pop up in the future for alleles that might trigger this bug:
![image](https://github.com/DKMS-LSL/typeloader/assets/43027482/70a2ed5c-8d0c-49bc-9c05-acd9f77a8be4)

This will be contained in the upcoming release.

I'm very sorry I can't do better in this case. It really bugs me, but my time is bound by other projects.

**Comment by stephencheunghk** [comment]
Thanks for the efforts and updates!


> Be aware, though, that you will sadly probably have to do the same thing again when you do IPD submission, as there is a re-BLAST-step in there... :( (Maybe make a fake-IPD-submission on your test account with the "no T insertion" variant to see the outcome?)

You previously mentioned that the annotation may have to be amended again during IPD submission. May I know how to do so? Because I found that the annotations in some of the IPD submission files generated are not exactly expected (e.g. not the commonest allele chosen, shifting of codon number in DQB1 locus due to Exon 5). If possible, I would like to amend it before the submission to IPD.

**Comment by bmschoene** [comment]
TypeLoader does not know or care about how common a reference allele is. It chooses the closest allele purely based on BLAST similarity. So far, IPD has never minded this, in the several thousand alleles we have submitted. 
The IPD files will state which allele TypeLoader used as closest allele.
(I know it would be more practical to see this information earlier. In the new release, it will at least be written to the log files during allele upload. That's all I could find the time for.)

As for amending the files before submitting, this is easy. While the menu says "IPD submission", TypeLoader has no direct access to IPD upload servers. It can just create the submission files and then offer them to you for download. These are text files and you can edit them manually however you see fit before submitting them. (In the beginning, you won't be able to submit files directly to IPD, anyway, but rather will have to use their web portal for a couple of alleles, [as described in the user menu](https://github.com/DKMS-LSL/typeloader/blob/master/user_manual/ipd.md). I'm sorry about that, it's what IPD wants, and we have no influence on their acceptance procedure.

As for your concrete allele: this issue will probably become void with the new release. Apparently, there is a new closest allele in HLA 3.56.0 that does not create this problem. But to use HLA 3.56.0, you will need the new TypeLoader.
(I was hoping to have the release up today, but have run into problems at GitHub with LFS. I'll upload the new release as soon as I can.)

**Comment by bmschoene** [comment]
The new TypeLoader release is up: https://github.com/DKMS-LSL/typeloader/releases/tag/2.15.0
